default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?stage?', '_dev') %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?stage?', '_test') %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?stage?', '_staging') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?stage?', '_production') %>
